import cv2
img1 = cv2.imread("watch.jpeg")
img2 = cv2.imread("watch2.jpeg")
query_gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
target_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
orb = cv2.ORB_create()
kp1, des1 = orb.detectAndCompute(query_gray, None)
kp2, des2 = orb.detectAndCompute(target_gray, None)
bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
matches = bf.match(des1, des2)
matches = sorted(matches, key=lambda x: x.distance)
img_matches = cv2.drawMatches(img1, kp1, img2, kp2, matches[:10], None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
cv2.imshow("Object Detection", img_matches)
cv2.waitKey(0)
cv2.destroyAllWindows()